title: "(12/30)大家一起学Blazor：Cascading values and parameters"
slug: 12-of-30-let-us-learn-blazor-together-cascading-values-and-parameters
description: "昨天不小心把Reset按钮的type改成button，今天改回reset。"
date: 2021-12-15 23:38:24
lastmod: 2021-12-15 23:38:24
author: StrayaWorker
originalTitle: "(12/30)大家一起学Blazor：Cascading values and parameters"
originalLink: https://ithelp.ithome.com.tw/articles/10262797
copyright: Reprinted
draft: false
cover: https://img1.dotnet9.com/2021/12/cover_05.png
categories:
  - Blazor
albums:
  - 一起学Blazor系列
tags:
  - .NET
  - C#
  - ASP.NET Core
  - Blazor
