title: "劳动仲裁回忆录（一）：提交仲裁申请"
slug: memoir-of-labor-arbitration-1-submit-an-application-for-arbitration
description: 个人全程劳动仲裁实录
date: 2022-03-17 23:05:13
lastmod: 2022-03-17 23:05:13
author: 逃离沙漠
originalTitle: "劳动仲裁回忆录（一）：提交仲裁申请"
originalLink: https://mp.weixin.qq.com/s/jBIbbEU2FPhMJDg78uvioQ
copyright: Reprinted
draft: false
cover: https://img1.dotnet9.com/2022/03/cover_12.jpeg
categories:
  - 分享
tags:
  - 劳动仲裁
