title: "如何提升.NET 控制台应用体验？"
slug: how-to-improve-net-console-application-experience
description: "来，教你写出酷炫的控制台应用"
date: 2022-04-04 11:21:39
lastmod: 2022-04-04 11:21:39
author: 古道轻风
originalTitle: "如何提升.NET 控制台应用体验？"
originalLink: https://www.cnblogs.com/88223100/p/upgraded-dotnet-console-experience.html
copyright: Reprinted
draft: false
cover: https://img1.dotnet9.com/2022/04/0201.png
categories:
  - .NET
albums:
  - C#开源项目
tags:
  - .NET
  - C#
  - 控制台
  - 酷炫的控制台
