title: "Maui学习之路(2)-Mac窗体设置"
slug: maui-learning-road-one-mac-form-settings
description: "发现微软官网的`UIKit`官方文档居然比`Apple`提供的还要全面"
date: 2022-06-02 21:21:27
lastmod: 2022-06-02 21:21:27
author: 轩研 WPF开发者
originalTitle: "Maui学习之路(2)-Mac窗体设置"
originalLink: https://mp.weixin.qq.com/s/G3hhhl4L3MYi_74_AV_ybg
copyright: Reprinted
draft: false
cover: https://img1.dotnet9.com/2022/06/0208.png
categories:
  - MAUI
tags:
  - .NET
  - MAUI
